//! SeaORM Entity. Generated by sea-orm-codegen 0.7.0

use sea_orm::entity::prelude::*;
use sea_orm::Iterable;
use sea_orm::strum::IntoEnumIterator;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "chapters")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub manga_id: i32,
    pub translator_id: i32,
    pub chapter_id: String,
    pub link: String,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl Iterable for Relation {
    type Iterator = ();

    fn iter() -> Self::Iterator {
        
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
