//! SeaORM Entity. Generated by sea-orm-codegen 0.7.0

use sea_orm::entity::prelude::*;

pub enum BookType {
    Manga,
    Ranobe
}

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "book")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub group_id: i32,
    pub book_type: BookType,
    pub title: String,
    pub description: String,
    pub img: String,
}


#[derive(Copy, Clone, Debug, EnumIter, Iterable)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!()
    }
}

impl ActiveModelBehavior for ActiveModel {}
